# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Capture_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.widget_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_3 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.ImageView_Preview = ImageView(self.splitter_2)
        self.ImageView_Preview.setObjectName("ImageView_Preview")
        self.plainTextEdit_Log = QtWidgets.QPlainTextEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Log.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Log.setSizePolicy(sizePolicy)
        self.plainTextEdit_Log.setObjectName("plainTextEdit_Log")
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 353, 695))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_PreviewFlipH = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_PreviewFlipH.setObjectName("checkBox_PreviewFlipH")
        self.gridLayout_2.addWidget(self.checkBox_PreviewFlipH, 0, 1, 1, 1)
        self.comboBox_LoadSettings = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_LoadSettings.setObjectName("comboBox_LoadSettings")
        self.gridLayout_2.addWidget(self.comboBox_LoadSettings, 3, 0, 1, 2)
        self.checkBox_PreviewFlipV = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_PreviewFlipV.setObjectName("checkBox_PreviewFlipV")
        self.gridLayout_2.addWidget(self.checkBox_PreviewFlipV, 0, 2, 1, 1)
        self.widget_Params = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Params.sizePolicy().hasHeightForWidth())
        self.widget_Params.setSizePolicy(sizePolicy)
        self.widget_Params.setObjectName("widget_Params")
        self.gridLayout_2.addWidget(self.widget_Params, 2, 0, 1, 3)
        self.pushButton_CameraSaveSettings = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_CameraSaveSettings.setObjectName("pushButton_CameraSaveSettings")
        self.gridLayout_2.addWidget(self.pushButton_CameraSaveSettings, 3, 2, 1, 1)
        self.comboBox_PreviewRot = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_PreviewRot.setObjectName("comboBox_PreviewRot")
        self.comboBox_PreviewRot.addItem("")
        self.comboBox_PreviewRot.addItem("")
        self.comboBox_PreviewRot.addItem("")
        self.comboBox_PreviewRot.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_PreviewRot, 0, 0, 1, 1)
        self.checkBox_RawPreview = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_RawPreview.setObjectName("checkBox_RawPreview")
        self.gridLayout_2.addWidget(self.checkBox_RawPreview, 1, 0, 1, 1)
        self.comboBox_RawPreviewMode = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_RawPreviewMode.setEnabled(False)
        self.comboBox_RawPreviewMode.setObjectName("comboBox_RawPreviewMode")
        self.comboBox_RawPreviewMode.addItem("")
        self.comboBox_RawPreviewMode.addItem("")
        self.comboBox_RawPreviewMode.addItem("")
        self.comboBox_RawPreviewMode.addItem("")
        self.comboBox_RawPreviewMode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_RawPreviewMode, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_ImageInfos = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_ImageInfos.setMinimumSize(QtCore.QSize(0, 250))
        self.plainTextEdit_ImageInfos.setReadOnly(True)
        self.plainTextEdit_ImageInfos.setObjectName("plainTextEdit_ImageInfos")
        self.verticalLayout.addWidget(self.plainTextEdit_ImageInfos)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_RecordRaw = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_RecordRaw.setChecked(True)
        self.checkBox_RecordRaw.setObjectName("checkBox_RecordRaw")
        self.gridLayout.addWidget(self.checkBox_RecordRaw, 2, 6, 1, 1)
        self.spinBox_nImagesToRecord = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_nImagesToRecord.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_nImagesToRecord.setMinimum(1)
        self.spinBox_nImagesToRecord.setMaximum(999999)
        self.spinBox_nImagesToRecord.setObjectName("spinBox_nImagesToRecord")
        self.gridLayout.addWidget(self.spinBox_nImagesToRecord, 2, 1, 1, 3)
        self.pushButton_Folder = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Folder.setObjectName("pushButton_Folder")
        self.gridLayout.addWidget(self.pushButton_Folder, 0, 0, 1, 2)
        self.lineEdit_ImageComment = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ImageComment.setObjectName("lineEdit_ImageComment")
        self.gridLayout.addWidget(self.lineEdit_ImageComment, 1, 1, 1, 6)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.pushButton_StartRec = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_StartRec.setObjectName("pushButton_StartRec")
        self.gridLayout.addWidget(self.pushButton_StartRec, 3, 0, 1, 2)
        self.doubleSpinBox_TimeLapse = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_TimeLapse.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_TimeLapse.setSizePolicy(sizePolicy)
        self.doubleSpinBox_TimeLapse.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_TimeLapse.setPrefix("")
        self.doubleSpinBox_TimeLapse.setDecimals(1)
        self.doubleSpinBox_TimeLapse.setMaximum(1000000.0)
        self.doubleSpinBox_TimeLapse.setObjectName("doubleSpinBox_TimeLapse")
        self.gridLayout.addWidget(self.doubleSpinBox_TimeLapse, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 4, 1, 1)
        self.lineEdit_FileName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.gridLayout.addWidget(self.lineEdit_FileName, 0, 4, 1, 3)
        self.pushButton_StopRec = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_StopRec.setEnabled(False)
        self.pushButton_StopRec.setObjectName("pushButton_StopRec")
        self.gridLayout.addWidget(self.pushButton_StopRec, 3, 4, 1, 3)
        self.label_RecordedImageCounter = QtWidgets.QLabel(self.groupBox)
        self.label_RecordedImageCounter.setObjectName("label_RecordedImageCounter")
        self.gridLayout.addWidget(self.label_RecordedImageCounter, 3, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 26))
        self.menubar.setObjectName("menubar")
        self.menuAutomation = QtWidgets.QMenu(self.menubar)
        self.menuAutomation.setObjectName("menuAutomation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_DarkNoiseMeasurement = QtWidgets.QAction(MainWindow)
        self.action_DarkNoiseMeasurement.setObjectName("action_DarkNoiseMeasurement")
        self.menuAutomation.addAction(self.action_DarkNoiseMeasurement)
        self.menubar.addAction(self.menuAutomation.menuAction())

        self.retranslateUi(MainWindow)
        self.checkBox_RawPreview.clicked['bool'].connect(self.comboBox_RawPreviewMode.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Camera Settings"))
        self.checkBox_PreviewFlipH.setText(_translate("MainWindow", "flip H"))
        self.checkBox_PreviewFlipV.setText(_translate("MainWindow", "flip V"))
        self.pushButton_CameraSaveSettings.setText(_translate("MainWindow", "Save"))
        self.comboBox_PreviewRot.setItemText(0, _translate("MainWindow", "0deg"))
        self.comboBox_PreviewRot.setItemText(1, _translate("MainWindow", "90deg"))
        self.comboBox_PreviewRot.setItemText(2, _translate("MainWindow", "180deg"))
        self.comboBox_PreviewRot.setItemText(3, _translate("MainWindow", "270deg"))
        self.checkBox_RawPreview.setText(_translate("MainWindow", "RAW Preview"))
        self.comboBox_RawPreviewMode.setItemText(0, _translate("MainWindow", "gray"))
        self.comboBox_RawPreviewMode.setItemText(1, _translate("MainWindow", "red"))
        self.comboBox_RawPreviewMode.setItemText(2, _translate("MainWindow", "green 1"))
        self.comboBox_RawPreviewMode.setItemText(3, _translate("MainWindow", "green 2"))
        self.comboBox_RawPreviewMode.setItemText(4, _translate("MainWindow", "blue"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Frame Infos"))
        self.groupBox.setTitle(_translate("MainWindow", "Recording"))
        self.checkBox_RecordRaw.setText(_translate("MainWindow", "RAW"))
        self.pushButton_Folder.setText(_translate("MainWindow", "Folder"))
        self.label_3.setText(_translate("MainWindow", "Prefix:"))
        self.label_2.setText(_translate("MainWindow", "Comment:"))
        self.label_4.setText(_translate("MainWindow", "# Images:"))
        self.pushButton_StartRec.setText(_translate("MainWindow", "Rec"))
        self.doubleSpinBox_TimeLapse.setSuffix(_translate("MainWindow", " sec"))
        self.label.setText(_translate("MainWindow", "every"))
        self.pushButton_StopRec.setText(_translate("MainWindow", "Stop"))
        self.label_RecordedImageCounter.setText(_translate("MainWindow", "0"))
        self.menuAutomation.setTitle(_translate("MainWindow", "Automation"))
        self.action_DarkNoiseMeasurement.setText(_translate("MainWindow", "Dark Noise Measurement"))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

